name: _deploy

on:
  workflow_call:
    inputs:
      bucket_name:
        required: true
        type: string
      distribution_id:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.12.0'

      - name: Install dependencies
        run: yarn install

      - name: Build & Export
        run: yarn build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_SOCIAL_LOGIN_BASE_URL: ${{ vars.VITE_SOCIAL_LOGIN_BASE_URL }}

      - name: Deploy to S3 and Invalidate Cloudfront
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WAFFLE_CICD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WAFFLE_CICD_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
        run: |
          aws s3 sync ./dist s3://${{ inputs.bucket_name }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ inputs.distribution_id }} --paths "/*"
