name: deploy-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      bucket_name: hangsha-web-prod
      distribution_id: E1UQAE6HOA8O14
      ga_measurement_id: ${{ vars.VITE_GA_MEASUREMENT_ID_PROD }}
      social_login_base_url: ${{ vars.VITE_SOCIAL_LOGIN_BASE_URL_PROD }}
    secrets: inherit
