name: deploy-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      bucket_name: hangsha-web-dev
      distribution_id: E3FWQLYH2W4XLU
      ga_measurement_id: ${{ vars.VITE_GA_MEASUREMENT_ID_DEV }}
      social_login_base_url: ${{ vars.VITE_SOCIAL_LOGIN_BASE_URL_DEV }}
    secrets: inherit
