name: pr_check-dev

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/_pr_check.yml
    with:
      ga_measurement_id: ${{ vars.VITE_GA_MEASUREMENT_ID_DEV }}
      social_login_base_url: ${{ vars.VITE_SOCIAL_LOGIN_BASE_URL_DEV }}